"""WHOLE_LIFE product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from annuity_model.build_wl_excel_workbook import WLExcelBuildSpec
from annuity_model.product_excel import _BUILDER_REGISTRY
from annuity_model.product_registry import ProductCapabilities, ProductType, _validate_wl
from annuity_model.products import ProductDefinition, register_product
from annuity_model.products.whole_life.ui import (
    WHOLE_LIFE_ADAPTER,
    whole_life_metric_formatter,
    whole_life_ui_config,
)
from annuity_model.wl_projection import (
    WLContract,
    WLProjectionResult,
    liability_path_from_wl_projection,
    price_wl_single_premium,
)

DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.WHOLE_LIFE,
        display_name="Whole Life (single premium)",
        contract_type=WLContract,
        result_type=WLProjectionResult,
        builder_spec_type=WLExcelBuildSpec,
        adapter=WHOLE_LIFE_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.WHOLE_LIFE],
        liability_path_converter=liability_path_from_wl_projection,
        metric_formatter=whole_life_metric_formatter,
        capabilities=ProductCapabilities(
            supports_economic_scenario=False, supports_monte_carlo=False
        ),
        ui_config=whole_life_ui_config,
        mortality_mode_options=("cso_2017_ult", "qx_csv", "synthetic"),
        default_mortality_mode="cso_2017_ult",
        validator=_validate_wl,
        order=6,
    )
)


__all__ = [
    "DEFINITION",
    "WLContract",
    "WLExcelBuildSpec",
    "WLProjectionResult",
    "WHOLE_LIFE_ADAPTER",
    "liability_path_from_wl_projection",
    "price_wl_single_premium",
    "whole_life_metric_formatter",
    "whole_life_ui_config",
]
