"""VARIABLE_ANNUITY product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from annuity_model.build_va_excel_workbook import VAExcelBuildSpec
from annuity_model.product_excel import _BUILDER_REGISTRY
from annuity_model.product_registry import ProductCapabilities, ProductType, _validate_va
from annuity_model.products import ProductDefinition, register_product
from annuity_model.products.variable_annuity.ui import (
    VARIABLE_ANNUITY_ADAPTER,
    variable_annuity_metric_formatter,
    variable_annuity_ui_config,
)
from annuity_model.va_projection import (
    VAContract,
    VAProjectionResult,
    liability_path_from_va_projection,
    price_va_single_premium,
    price_va_single_premium_monte_carlo,
)

DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.VARIABLE_ANNUITY,
        display_name="Variable Annuity (single premium)",
        contract_type=VAContract,
        result_type=VAProjectionResult,
        builder_spec_type=VAExcelBuildSpec,
        adapter=VARIABLE_ANNUITY_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.VARIABLE_ANNUITY],
        liability_path_converter=liability_path_from_va_projection,
        metric_formatter=variable_annuity_metric_formatter,
        capabilities=ProductCapabilities(
            supports_economic_scenario=True, supports_monte_carlo=True
        ),
        ui_config=variable_annuity_ui_config,
        mortality_mode_options=("synthetic", "qx_csv", "rp2014_mp2016"),
        default_mortality_mode="rp2014_mp2016",
        validator=_validate_va,
        order=5,
    )
)


__all__ = [
    "DEFINITION",
    "VAContract",
    "VAExcelBuildSpec",
    "VAProjectionResult",
    "VARIABLE_ANNUITY_ADAPTER",
    "liability_path_from_va_projection",
    "price_va_single_premium",
    "price_va_single_premium_monte_carlo",
    "variable_annuity_metric_formatter",
    "variable_annuity_ui_config",
]
