"""INDEXED_UL product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from annuity_model.build_iul_excel_workbook import IULExcelBuildSpec
from annuity_model.iul_projection import (
    IULContract,
    IULProjectionResult,
    liability_path_from_iul_projection,
    price_iul_single_premium,
    price_iul_single_premium_monte_carlo,
)
from annuity_model.product_excel import _BUILDER_REGISTRY
from annuity_model.product_registry import ProductCapabilities, ProductType, _validate_iul
from annuity_model.products import ProductDefinition, register_product
from annuity_model.products.indexed_ul.ui import (
    INDEXED_UL_ADAPTER,
    indexed_ul_metric_formatter,
    indexed_ul_ui_config,
)

DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.INDEXED_UL,
        display_name="Indexed UL (IUL, single premium)",
        contract_type=IULContract,
        result_type=IULProjectionResult,
        builder_spec_type=IULExcelBuildSpec,
        adapter=INDEXED_UL_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.INDEXED_UL],
        liability_path_converter=liability_path_from_iul_projection,
        metric_formatter=indexed_ul_metric_formatter,
        capabilities=ProductCapabilities(
            supports_economic_scenario=True, supports_monte_carlo=True
        ),
        ui_config=indexed_ul_ui_config,
        mortality_mode_options=("cso_2017_ult", "qx_csv", "synthetic"),
        default_mortality_mode="cso_2017_ult",
        validator=_validate_iul,
        order=8,
    )
)


__all__ = [
    "DEFINITION",
    "IULContract",
    "IULExcelBuildSpec",
    "IULProjectionResult",
    "INDEXED_UL_ADAPTER",
    "liability_path_from_iul_projection",
    "price_iul_single_premium",
    "price_iul_single_premium_monte_carlo",
    "indexed_ul_metric_formatter",
    "indexed_ul_ui_config",
]
