"""VARIABLE_UL product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from product_registry import ProductType, product_label

from products import ProductDefinition, register_product
from vul_projection import (
    VULContract,
    VULProjectionResult,
    liability_path_from_vul_projection,
    price_vul_single_premium,
    price_vul_single_premium_monte_carlo,
)
from build_vul_excel_workbook import VULExcelBuildSpec

from product_excel import _BUILDER_REGISTRY
from products.variable_ul.ui import VARIABLE_UL_ADAPTER, variable_ul_metric_formatter


DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.VARIABLE_UL,
        display_name=product_label(ProductType.VARIABLE_UL),
        contract_type=VULContract,
        result_type=VULProjectionResult,
        builder_spec_type=VULExcelBuildSpec,
        adapter=VARIABLE_UL_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.VARIABLE_UL],
        liability_path_converter=liability_path_from_vul_projection,
        metric_formatter=variable_ul_metric_formatter,
    )
)


__all__ = [
    "DEFINITION",
    "VULContract",
    "VULExcelBuildSpec",
    "VULProjectionResult",
    "VARIABLE_UL_ADAPTER",
    "liability_path_from_vul_projection",
    "price_vul_single_premium",
    "variable_ul_metric_formatter",
]
