"""Generate synthetic placeholder CSO-2017-shape mortality CSVs.

These are NOT licensed CSO data. They are simple Gompertz-Makeham
proxies whose age curve is *shaped* like CSO Ultimate but whose
absolute values must NOT be cited as actuarial assumptions. Production
deployments overlay their own licensed CSO 2017 Ultimate file at the
same paths (the loader tolerates either source).

Run from the annuity_model directory::

    python scripts/generate_cso_2017_synthetic.py

This emits four files under data/mortality/cso_2017_ult/.
"""

from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT_DIR = ROOT / "data" / "mortality" / "cso_2017_ult"


def _gompertz_makeham(
    *, ages: np.ndarray, a: float, b: float, c: float, cap: float = 0.999
) -> np.ndarray:
    """Return clipped q_x = min(cap, a + b * exp(c * x))."""
    qx = a + b * np.exp(c * ages)
    return np.clip(qx, 0.0, cap)


def _build_table(
    *,
    sex: str,
    smoker_class: str,
    a: float,
    b: float,
    c: float,
    smoker_mult: float = 1.0,
    sex_mult: float = 1.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Generate (ages, qx) for the requested cohort.

    The Gompertz-Makeham parameters are chosen so the resulting curve
    is in the ballpark of published CSO Ultimate shapes (low at young
    ages, rising exponentially through middle age, hitting plausibly
    high values past age 100). Smoker / female multipliers tilt the
    curve appropriately for each cohort.
    """
    ages = np.arange(0, 121, dtype=int)
    qx = _gompertz_makeham(ages=ages, a=a, b=b, c=c)
    qx = qx * smoker_mult * sex_mult
    qx = np.clip(qx, 0.0, 0.999)
    return ages, qx


README_TEXT = """# CSO 2017 Ultimate placeholder data

The CSV files in this directory are **synthetic Gompertz-Makeham
approximations** generated by ``scripts/generate_cso_2017_synthetic.py``,
NOT the licensed CSO 2017 Ultimate mortality table.

The shape of the curve roughly follows published CSO Ultimate
(low at young ages, exponentially rising through middle age, capping
out near 1.0 past age 100). The absolute values must NOT be cited as
actuarial assumptions in any deliverable.

## Production usage

Overlay your own licensed CSO 2017 Ultimate file at the SAME path
(same filename, same column layout: ``age,qx``). The loader
(``mortality_2017_cso.MortalityTable2017CSO.load``) does not
distinguish synthetic vs licensed -- both are valid CSV inputs -- so
the swap is a file overlay, not a code change.

## Files

| Filename | Cohort | Synthetic multiplier vs male NS base |
|----------|--------|--------------------------------------|
| ``cso_2017_ult_male_nonsmoker_qx.csv`` | Male NS | 1.0 (base) |
| ``cso_2017_ult_female_nonsmoker_qx.csv`` | Female NS | 0.70 |
| ``cso_2017_ult_male_smoker_qx.csv`` | Male SK | 2.20 |
| ``cso_2017_ult_female_smoker_qx.csv`` | Female SK | 2.20 * 0.70 = 1.54 |

After regeneration, update the SHAs in ``data_registry.REGISTRY``
(``test_data_registry_invariants.py`` will print the new digest).
"""


def _write(path: Path, ages: np.ndarray, qx: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # ``newline="\n"`` forces LF endings on every platform so the on-disk
    # bytes match ``.gitattributes`` (``*.csv text eol=lf``); without
    # this, the csv module's default ``"\r\n"`` lineterminator would
    # write CRLF and ``data_registry`` SHAs would drift after a Git
    # checkout normalisation.
    with path.open("w", encoding="utf-8", newline="\n") as fh:
        writer = csv.writer(fh, lineterminator="\n")
        writer.writerow(["age", "qx"])
        for a, q in zip(ages.tolist(), qx.tolist(), strict=True):
            writer.writerow([int(a), f"{float(q):.6f}"])


def _write_readme(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(README_TEXT, encoding="utf-8")


def main() -> int:
    # Calibrated so the male NS curve hits roughly:
    #   age 25 ~ 0.0007, age 45 ~ 0.0027, age 65 ~ 0.012, age 85 ~ 0.085
    # which is the same order of magnitude as published CSO 2017 Ultimate.
    BASE_A, BASE_B, BASE_C = 4.5e-4, 4.5e-5, 0.094

    male_ns = _build_table(
        sex="male", smoker_class="nonsmoker",
        a=BASE_A, b=BASE_B, c=BASE_C,
        smoker_mult=1.0, sex_mult=1.0,
    )
    female_ns = _build_table(
        sex="female", smoker_class="nonsmoker",
        a=BASE_A, b=BASE_B, c=BASE_C,
        smoker_mult=1.0, sex_mult=0.70,  # female ~30% lower
    )
    male_sk = _build_table(
        sex="male", smoker_class="smoker",
        a=BASE_A, b=BASE_B, c=BASE_C,
        smoker_mult=2.20, sex_mult=1.0,  # smoker ~2.2x non-smoker
    )
    female_sk = _build_table(
        sex="female", smoker_class="smoker",
        a=BASE_A, b=BASE_B, c=BASE_C,
        smoker_mult=2.20, sex_mult=0.70,
    )

    _write(OUT_DIR / "cso_2017_ult_male_nonsmoker_qx.csv", *male_ns)
    _write(OUT_DIR / "cso_2017_ult_female_nonsmoker_qx.csv", *female_ns)
    _write(OUT_DIR / "cso_2017_ult_male_smoker_qx.csv", *male_sk)
    _write(OUT_DIR / "cso_2017_ult_female_smoker_qx.csv", *female_sk)
    _write_readme(OUT_DIR / "README.md")
    print(f"Wrote 4 synthetic CSO-2017 files + README under {OUT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
