"""Scaffold a new product subpackage end-to-end.

Adding a new product to the platform requires touching ~10 places that
have grown in step (engine module, Excel builder, registry, dispatch
converter, liability layout, products subpackage shim, parity test, ...).
This script generates the boilerplate so contributors only fill in the
actuarial logic.

Usage
-----

    python scripts/scaffold_product.py --code fia \\
        --display-name "FIA (S&P-linked, deterministic)" \\
        --contract-class FIAContract \\
        --result-class FIAProjectionResult

What it generates (all under ``annuity_model/``):

* ``products/<code>/__init__.py``  -- ``register_product`` shim
* ``products/<code>/schema.py``    -- contract/result re-export shim
* ``products/<code>/engine.py``    -- pricing entry-point re-export shim
* ``products/<code>/excel.py``     -- Excel builder re-export shim
* ``products/<code>/ui.py``        -- adapter + UI config re-export shim

Then prints a checklist of follow-up TODOs the contributor must do
manually (because they require domain knowledge the script cannot
synthesise):

* Implement ``<code>_projection.py`` (engine) and
  ``build_<code>_excel_workbook.py`` (Excel builder).
* Add the ``ProductType.<UPPER_CODE>`` enum member to
  :mod:`product_registry`.
* Register a liability-path converter via
  :func:`liability_dispatch.register_liability_path_converter`.
* Add a ``LiabilityLayout`` to :data:`liability_layouts.LIABILITY_LAYOUTS`.
* Add an entry to :data:`product_excel._BUILDER_REGISTRY` via the
  ``@register_builder`` decorator.

The meta-tests under ``tests/test_meta_invariants.py`` and
``tests/test_products_registry.py`` will keep failing until every wire
above is in place; that is intentional -- they ARE the new-product
checklist.

Idempotent: refuses to overwrite existing files unless ``--force``
is passed.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from textwrap import dedent

# Resolve annuity_model/ from this script's location so the tool runs
# regardless of cwd.
ANNUITY_ROOT = Path(__file__).resolve().parent.parent
PRODUCTS_DIR = ANNUITY_ROOT / "products"


_CODE_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")


def _validate_code(code: str) -> str:
    if not _CODE_PATTERN.match(code):
        raise SystemExit(
            f"--code must be lowercase ASCII letters/digits/underscores, starting "
            f"with a letter (got {code!r}). Examples: fia, va_glwb, ulsg."
        )
    return code


def _validate_class_name(name: str, *, label: str) -> str:
    if not re.match(r"^[A-Z][A-Za-z0-9_]*$", name):
        raise SystemExit(
            f"--{label} must be a valid Python class name in PascalCase "
            f"(got {name!r}). Example: FIAContract."
        )
    return name


def _write_file(path: Path, contents: str, *, force: bool) -> None:
    if path.exists() and not force:
        raise SystemExit(
            f"refusing to overwrite existing file: {path} (pass --force to overwrite)."
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents)
    print(f"  wrote {path.relative_to(ANNUITY_ROOT)}")


def _render_init(code: str, display_name: str, contract: str, result: str) -> str:
    enum_member = code.upper()
    return dedent(
        f'''\
        """{display_name} product subpackage.

        Generated by ``scripts/scaffold_product.py``. See ``products.spia``
        for the pattern; this module is the {display_name} analog.
        """

        from __future__ import annotations

        from product_registry import ProductType, product_label

        from products import ProductDefinition, register_product
        from products.{code}.engine import (
            {contract},
            {result},
        )
        from products.{code}.excel import {enum_member}_BUILD_SPEC, build_{code}_workbook
        from products.{code}.ui import {enum_member}_ADAPTER, {code}_metric_formatter


        # TODO(scaffolded {code}): once the engine + Excel builder land, replace
        # the placeholder converter / builder references below with the real
        # callables. Until then this import will fail at module load time and
        # ``products.discover_products()`` will surface the missing wires.
        from products.{code}.engine import liability_path_from_{code}_projection
        from product_excel import _BUILDER_REGISTRY


        DEFINITION = register_product(
            ProductDefinition(
                product_type=ProductType.{enum_member},
                display_name=product_label(ProductType.{enum_member}),
                contract_type={contract},
                result_type={result},
                builder_spec_type={enum_member}_BUILD_SPEC,
                adapter={enum_member}_ADAPTER,
                builder=_BUILDER_REGISTRY[ProductType.{enum_member}],
                liability_path_converter=liability_path_from_{code}_projection,
                metric_formatter={code}_metric_formatter,
            )
        )


        __all__ = [
            "DEFINITION",
            "{contract}",
            "{enum_member}_ADAPTER",
            "{enum_member}_BUILD_SPEC",
            "{result}",
            "build_{code}_workbook",
            "liability_path_from_{code}_projection",
            "{code}_metric_formatter",
        ]
        '''
    )


def _render_schema(code: str, contract: str, result: str) -> str:
    return dedent(
        f'''\
        """{contract} + {result} dataclasses (re-export shim).

        Generated by ``scripts/scaffold_product.py``. Implementation lives in
        :mod:`{code}_projection`. Edit that module, then update the imports
        below.
        """

        from __future__ import annotations

        from {code}_projection import {contract}, {result}

        __all__ = ["{contract}", "{result}"]
        '''
    )


def _render_engine(code: str, contract: str, result: str) -> str:
    return dedent(
        f'''\
        """{code} pricing + ALM engine surface (re-export shim).

        Generated by ``scripts/scaffold_product.py``.
        """

        from __future__ import annotations

        from {code}_projection import (
            {contract},
            {result},
            liability_path_from_{code}_projection,
            price_{code},
        )

        __all__ = [
            "{contract}",
            "{result}",
            "liability_path_from_{code}_projection",
            "price_{code}",
        ]
        '''
    )


def _render_excel(code: str) -> str:
    enum_member = code.upper()
    return dedent(
        f'''\
        """{code} Excel build-spec + builder (re-export shim).

        Generated by ``scripts/scaffold_product.py``. Implementation lives
        in :mod:`build_{code}_excel_workbook`.
        """

        from __future__ import annotations

        from build_{code}_excel_workbook import (
            {enum_member}_BUILD_SPEC,
            build_{code}_workbook,
            {code}_excel_spec_from_launcher,
        )

        __all__ = [
            "{enum_member}_BUILD_SPEC",
            "build_{code}_workbook",
            "{code}_excel_spec_from_launcher",
        ]
        '''
    )


def _render_ui(code: str) -> str:
    enum_member = code.upper()
    return dedent(
        f'''\
        """{code} adapter, metric formatter, and UI config (re-export shim).

        Generated by ``scripts/scaffold_product.py``.
        """

        from __future__ import annotations

        from product_registry import (
            ProductType,
            _PRICING_METRIC_FORMATTERS,
            get_product_adapter,
            get_product_ui_config,
        )

        {enum_member}_ADAPTER = get_product_adapter(ProductType.{enum_member})
        {code}_metric_formatter = _PRICING_METRIC_FORMATTERS[ProductType.{enum_member}]
        {code}_ui_config = get_product_ui_config(ProductType.{enum_member})


        __all__ = [
            "{enum_member}_ADAPTER",
            "{code}_metric_formatter",
            "{code}_ui_config",
        ]
        '''
    )


def _print_followups(code: str, contract: str, result: str) -> None:
    enum_member = code.upper()
    print()
    print("=" * 72)
    print(f"Scaffolded products/{code}/. Manual follow-ups:")
    print("=" * 72)
    print(
        dedent(
            f"""\
              [ ] Add ``ProductType.{enum_member} = "{code}"`` to
                  product_registry.ProductType.
              [ ] Implement {code}_projection.py with at minimum:
                    - dataclass {contract}
                    - dataclass {result}
                    - def price_{code}(...) -> {result}
                    - def liability_path_from_{code}_projection(...) -> LiabilityPath
                    - At module bottom:
                        from liability_dispatch import register_liability_path_converter
                        register_liability_path_converter(
                            "{result}", liability_path_from_{code}_projection
                        )
              [ ] Implement build_{code}_excel_workbook.py with:
                    - dataclass {enum_member}_BUILD_SPEC
                    - def {code}_excel_spec_from_launcher(...) -> {enum_member}_BUILD_SPEC
                    - def build_{code}_workbook(...) -> bytes
                    - At module bottom:
                        @register_builder(ProductType.{enum_member}, spec_type={enum_member}_BUILD_SPEC)
                        def _build_{code}_wrapper(**kwargs) -> bytes: ...
              [ ] Add LIABILITY_LAYOUTS["{code}"] entry in liability_layouts.py.
              [ ] Add an adapter (subclass {enum_member}ProductAdapter or build a new one),
                  register it in product_registry._PRODUCT_ADAPTERS.
              [ ] Add an entry to product_registry._PRICING_METRIC_FORMATTERS.
              [ ] Add an entry to product_registry._PRODUCT_DISPLAY_NAME and
                  ProductCapabilities/UIConfig dicts.
              [ ] Add a parity test under tests/parity/test_{code}_parity.py
                  (copy tests/parity/test_term_parity.py as a template).
              [ ] Run `python scripts/deep_smoke.py` and `python -m pytest -q` --
                  the meta-invariant tests will tell you which wire is still missing.

            See annuity_model/README.md "Adding a new product" for the full
            walkthrough; this scaffold completes step 4 of that list.
            """
        )
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--code", required=True, help="lowercase product code, e.g. fia, va_glwb")
    parser.add_argument(
        "--display-name", required=True, help='human-readable name, e.g. "FIA (S&P-linked)"'
    )
    parser.add_argument(
        "--contract-class",
        required=True,
        help="contract dataclass name in PascalCase, e.g. FIAContract",
    )
    parser.add_argument(
        "--result-class",
        required=True,
        help="pricing-result dataclass name in PascalCase, e.g. FIAProjectionResult",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing scaffolded files (use with care).",
    )
    args = parser.parse_args(argv)

    code = _validate_code(args.code)
    contract = _validate_class_name(args.contract_class, label="contract-class")
    result = _validate_class_name(args.result_class, label="result-class")
    display_name = args.display_name

    pkg_dir = PRODUCTS_DIR / code
    print(f"Scaffolding products/{code}/ ...")
    _write_file(
        pkg_dir / "__init__.py",
        _render_init(code, display_name, contract, result),
        force=args.force,
    )
    _write_file(pkg_dir / "schema.py", _render_schema(code, contract, result), force=args.force)
    _write_file(pkg_dir / "engine.py", _render_engine(code, contract, result), force=args.force)
    _write_file(pkg_dir / "excel.py", _render_excel(code), force=args.force)
    _write_file(pkg_dir / "ui.py", _render_ui(code), force=args.force)

    _print_followups(code, contract, result)
    return 0


if __name__ == "__main__":
    sys.exit(main())
