"""UNIVERSAL_LIFE product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from annuity_model.build_ul_excel_workbook import ULExcelBuildSpec
from annuity_model.product_excel import _BUILDER_REGISTRY
from annuity_model.product_registry import ProductCapabilities, ProductType, _validate_ul
from annuity_model.products import ProductDefinition, register_product
from annuity_model.products.universal_life.ui import (
    UNIVERSAL_LIFE_ADAPTER,
    universal_life_metric_formatter,
    universal_life_ui_config,
)
from annuity_model.ul_projection import (
    ULContract,
    ULProjectionResult,
    liability_path_from_ul_projection,
    price_ul_single_premium,
)

DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.UNIVERSAL_LIFE,
        display_name="Universal Life (single premium)",
        contract_type=ULContract,
        result_type=ULProjectionResult,
        builder_spec_type=ULExcelBuildSpec,
        adapter=UNIVERSAL_LIFE_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.UNIVERSAL_LIFE],
        liability_path_converter=liability_path_from_ul_projection,
        metric_formatter=universal_life_metric_formatter,
        capabilities=ProductCapabilities(
            supports_economic_scenario=False, supports_monte_carlo=False
        ),
        ui_config=universal_life_ui_config,
        mortality_mode_options=("cso_2017_ult", "qx_csv", "synthetic"),
        default_mortality_mode="cso_2017_ult",
        validator=_validate_ul,
        order=7,
    )
)


__all__ = [
    "DEFINITION",
    "ULContract",
    "ULExcelBuildSpec",
    "ULProjectionResult",
    "UNIVERSAL_LIFE_ADAPTER",
    "liability_path_from_ul_projection",
    "price_ul_single_premium",
    "universal_life_metric_formatter",
    "universal_life_ui_config",
]
