"""VARIABLE_UL product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from annuity_model.build_vul_excel_workbook import VULExcelBuildSpec
from annuity_model.product_excel import _BUILDER_REGISTRY
from annuity_model.product_registry import ProductCapabilities, ProductType, _validate_vul
from annuity_model.products import ProductDefinition, register_product
from annuity_model.products.variable_ul.ui import (
    VARIABLE_UL_ADAPTER,
    variable_ul_metric_formatter,
    variable_ul_ui_config,
)
from annuity_model.vul_projection import (
    VULContract,
    VULProjectionResult,
    liability_path_from_vul_projection,
    price_vul_single_premium,
    price_vul_single_premium_monte_carlo,
)

DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.VARIABLE_UL,
        display_name="Variable UL (VUL, single premium)",
        contract_type=VULContract,
        result_type=VULProjectionResult,
        builder_spec_type=VULExcelBuildSpec,
        adapter=VARIABLE_UL_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.VARIABLE_UL],
        liability_path_converter=liability_path_from_vul_projection,
        metric_formatter=variable_ul_metric_formatter,
        capabilities=ProductCapabilities(
            supports_economic_scenario=True, supports_monte_carlo=True
        ),
        ui_config=variable_ul_ui_config,
        mortality_mode_options=("cso_2017_ult", "qx_csv", "synthetic"),
        default_mortality_mode="cso_2017_ult",
        validator=_validate_vul,
        order=9,
    )
)


__all__ = [
    "DEFINITION",
    "VULContract",
    "VULExcelBuildSpec",
    "VULProjectionResult",
    "VARIABLE_UL_ADAPTER",
    "liability_path_from_vul_projection",
    "price_vul_single_premium",
    "price_vul_single_premium_monte_carlo",
    "variable_ul_metric_formatter",
    "variable_ul_ui_config",
]
