"""MYGA product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from annuity_model.build_myga_excel_workbook import MYGAExcelBuildSpec
from annuity_model.myga_projection import (
    MYGAContract,
    MYGAProjectionResult,
    liability_path_from_myga_projection,
    price_myga_single_premium,
)
from annuity_model.product_excel import _BUILDER_REGISTRY
from annuity_model.product_registry import ProductCapabilities, ProductType, _validate_myga
from annuity_model.products import ProductDefinition, register_product
from annuity_model.products.myga.ui import MYGA_ADAPTER, myga_metric_formatter, myga_ui_config

DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.MYGA,
        display_name="MYGA (multi-year guaranteed)",
        contract_type=MYGAContract,
        result_type=MYGAProjectionResult,
        builder_spec_type=MYGAExcelBuildSpec,
        adapter=MYGA_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.MYGA],
        liability_path_converter=liability_path_from_myga_projection,
        metric_formatter=myga_metric_formatter,
        capabilities=ProductCapabilities(
            supports_economic_scenario=False, supports_monte_carlo=False
        ),
        ui_config=myga_ui_config,
        mortality_mode_options=("synthetic", "qx_csv", "rp2014_mp2016"),
        default_mortality_mode="rp2014_mp2016",
        validator=_validate_myga,
        order=3,
    )
)


__all__ = [
    "DEFINITION",
    "MYGAContract",
    "MYGAExcelBuildSpec",
    "MYGAProjectionResult",
    "MYGA_ADAPTER",
    "liability_path_from_myga_projection",
    "price_myga_single_premium",
    "myga_metric_formatter",
    "myga_ui_config",
]
