"""
excel_formula_sim.py
--------------------
Python simulation of the ALM_Engine Excel formulas.

Used in parity tests to verify that the Excel formula logic (as generated by
alm_excel_ladder.py) produces the same results as spia_projection.py.

Any change to alm_excel_ladder.py formula logic must be reflected here, and
vice versa.  This file is the "executable specification" of the Excel formulas.
"""

from __future__ import annotations

import numpy as np

EXCEL_DISINVEST_EPSILON = 1e-9
EXCEL_DISINVEST_THRESHOLD = 5e-10


# ---------------------------------------------------------------------------
# Disinvestment — simulates ALM_Engine shortest-first disinvestment passes
# ---------------------------------------------------------------------------


def excel_disinvest_shortest_first(
    cash: float,
    faces: np.ndarray,
    t_rem: np.ndarray,
    df: np.ndarray,
    need: float,
) -> tuple[float, np.ndarray]:
    """Simulate Excel's multi-pass shortest-first disinvestment.

    Replicates the formula in alm_excel_ladder.py write_alm_engine_sheet():
        trnk[k] = t_re[k] + (k+1)*1E-9
        tmin     = MIN(IF(face[k]>1E-9, trnk[k], 999))
        sell[k]  = IF(AND(mode=1, face[k]>1E-9, ABS(trnk[k]-tmin)<5E-10),
                       MIN(face[k], need/df[k]), 0)

    Threshold is 5E-10 (half the inter-bucket epsilon interval of 1E-9) to
    ensure only the true minimum bucket is selected even when t_rem values
    differ by floating-point noise (~1e-16).

    Parameters
    ----------
    cash:   Cash balance before disinvestment (negative = deficit).
    faces:  Bond face amounts per bucket.
    t_rem:  Remaining tenor per bucket (years).
    df:     Discount factors per bucket (pre-computed at post-reinvest tenors).
    need:   Amount of cash to raise (positive).

    Returns
    -------
    (cash_after, faces_after)
    """
    faces = np.asarray(faces, dtype=float).copy()
    df = np.asarray(df, dtype=float).copy()
    nb = faces.shape[0]
    n_passes = nb + 2  # matches alm_excel_ladder.py n_dis

    n0 = float(need)
    c0 = float(cash)
    f0 = faces.copy()

    for _ in range(n_passes):
        if n0 <= 1e-9:
            break

        # Epsilon-adjusted tenor for each bucket; depleted buckets get sentinel 999
        trnk = np.array([
            t_rem[k] + (k + 1) * EXCEL_DISINVEST_EPSILON if f0[k] > 1e-9 else 999.0
            for k in range(nb)
        ])
        tmin = float(np.min(trnk))

        sells = np.zeros(nb)
        for k in range(nb):
            if f0[k] > 1e-9 and abs(trnk[k] - tmin) < EXCEL_DISINVEST_THRESHOLD:
                sells[k] = min(f0[k], n0 / max(df[k], 1e-15))

        pay = float(np.sum(sells * df))
        n0 = max(0.0, n0 - pay)
        c0 = c0 + pay
        f0 = np.maximum(0.0, f0 - sells)

    return c0, f0


# ---------------------------------------------------------------------------
# Reinvestment — simulates ALM_Engine pro-rata reinvestment
# ---------------------------------------------------------------------------


def excel_reinvest_pro_rata(
    cash: float,
    faces: np.ndarray,
    t_rem: np.ndarray,
    df: np.ndarray,
    w: np.ndarray,
    nominal_tenors: np.ndarray,
    xsr: float,
    gaps: np.ndarray,
    gap_sum: float,
) -> tuple[float, np.ndarray, np.ndarray]:
    """Simulate Excel's pro-rata reinvestment (dmv / f_re columns).

    Parameters
    ----------
    cash, faces, t_rem: portfolio state before reinvest.
    df:             discount factors at post-roll tenors.
    w:              target weights (index 0 = cash, 1..nb = bonds).
    nominal_tenors: nominal tenor in years per bucket.
    xsr:            cash surplus = cash - w[0]*aum_re.
    gaps:           bond[k] gap = max(0, w[k+1]*aum_re - mv[k]).
    gap_sum:        sum of positive gaps.

    Returns
    -------
    (cash_after, faces_after, t_rem_after)
    """
    faces = np.asarray(faces, dtype=float).copy()
    t_rem = np.asarray(t_rem, dtype=float).copy()
    nb = faces.shape[0]

    if xsr <= 1e-6 or gap_sum <= 1e-9:
        return cash, faces, t_rem

    for k in range(nb):
        if gaps[k] <= 0:
            continue
        split = gaps[k] / gap_sum
        dmv = xsr * split
        if dmv <= 0 or df[k] <= 1e-15:
            continue
        new_face = dmv / df[k]
        faces[k] += new_face
        cash -= dmv
        # Reset tenor to nominal for this bucket
        t_rem[k] = nominal_tenors[k]

    return cash, faces, t_rem
