"""
test_alm_parity.py
------------------
Cross-engine parity tests: Python ALM engine vs Excel formula simulation.

These tests verify that spia_projection.py and the Excel formulas generated by
alm_excel_ladder.py produce identical results for every tracked state variable
at every month of the projection horizon.

Run with:
    pytest tests/parity/ -v

All tests must pass with 0.00 discrepancy before any merge to main.
See docs/model_parity_contract.md for tolerance specifications.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pytest

# Ensure project root is importable
ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(ROOT))

import spia_projection as sp
from tests.parity.excel_formula_sim import (
    EXCEL_DISINVEST_EPSILON,
    EXCEL_DISINVEST_THRESHOLD,
    excel_disinvest_shortest_first,
)

# ---------------------------------------------------------------------------
# Tolerances (from docs/model_parity_contract.md)
# ---------------------------------------------------------------------------

TOL_DOLLAR = 1e-4   # cash, face, MV, surplus ($)
TOL_TENOR = 1e-6    # remaining tenor (years)
TOL_DF = 1e-10      # discount factor (dimensionless)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _flat_yc(rate: float) -> sp.YieldCurve:
    return sp.YieldCurve.from_flat_rate(rate)


def _df_rem(yc: sp.YieldCurve, t_arr: np.ndarray, spread: float = 0.0) -> np.ndarray:
    t = np.maximum(np.asarray(t_arr, dtype=float), 0.0)
    out = np.ones_like(t, dtype=float)
    mask = t > 1e-15
    if np.any(mask):
        out[mask] = yc.discount_factors(t[mask], spread=spread)
    return out


def _build_standard_buckets():
    """5-bucket allocation: 5% cash, 19% 1Y, 20% 3Y, 22% 5Y, 22% 10Y, 12% 20Y."""
    buckets = [
        sp.ALMBucketSpec(name="Cash", tenor_years=0),
        sp.ALMBucketSpec(name="1Y", tenor_years=1),
        sp.ALMBucketSpec(name="3Y", tenor_years=3),
        sp.ALMBucketSpec(name="5Y", tenor_years=5),
        sp.ALMBucketSpec(name="10Y", tenor_years=10),
        sp.ALMBucketSpec(name="20Y", tenor_years=20),
    ]
    weights = [0.05, 0.19, 0.20, 0.22, 0.22, 0.12]
    alloc = sp.ALMAllocationSpec(buckets=buckets, weights=weights)
    asm = sp.ALMAssumptions(
        allocation=alloc,
        rebalance_band=0.0,
        rebalance_frequency_months=12,
        reinvest_rule="pro_rata",
        disinvest_rule="shortest_first",
        rebalance_policy="full_target",
        liquidity_near_liquid_years=1.0,
    )
    return asm, np.array(weights), buckets


def _init_portfolio(aum: float, w: np.ndarray, buckets: list, yc: sp.YieldCurve, spread: float = 0.0):
    n_b = len(buckets) - 1
    nominal_tenors = np.array([float(b.tenor_years) for b in buckets[1:]])
    faces = np.zeros(n_b)
    t_rem = nominal_tenors.copy()
    for k in range(n_b):
        mv_t = w[k + 1] * aum
        d0 = float(yc.discount_factors(np.array([nominal_tenors[k]]), spread=spread)[0])
        faces[k] = mv_t / d0
    cash = float(w[0] * aum)
    return cash, faces, t_rem, nominal_tenors


def _run_full_sim(
    aum: float,
    cfs: np.ndarray,
    yc: sp.YieldCurve,
    use_excel_disinvest: bool = False,
    spread: float = 0.0,
) -> tuple[list, list, list]:
    """Run 60-month ALM step-by-step. Returns (cash_eom, face_eom, total_mv_eom) per month."""
    asm, w, buckets = _build_standard_buckets()
    cash, faces, t_rem, nominal_tenors = _init_portfolio(aum, w, buckets, yc, spread)
    dt = 1.0 / 12.0
    n_b = len(buckets) - 1

    cash_hist, face_hist, mv_hist = [], [], []

    for m in range(60):
        t_rem = np.maximum(t_rem - dt, 0.0)
        matured = (faces > 1e-15) & (t_rem <= 1e-14)
        for k in np.flatnonzero(matured):
            cash += float(faces[k])
            faces[k] = 0.0
        t_rem = np.where(faces <= 1e-15, 0.0, t_rem)
        df = _df_rem(yc, t_rem, spread)
        mv = faces * df

        if np.any(matured):
            cash, faces = sp._alm_micro_reinvest_pro_rata(
                cash=cash, faces=faces, t_rem=t_rem, w=w,
                yield_curve=yc, spread=spread, nominal_tenors=nominal_tenors,
            )
            df = _df_rem(yc, t_rem, spread)
            mv = faces * df

        cash -= float(cfs[m])
        need = max(0.0, -cash)
        if need > 1e-9:
            if use_excel_disinvest:
                cash, faces = excel_disinvest_shortest_first(cash, faces, t_rem, df, need)
            else:
                cash, faces = sp._alm_disinvest(
                    cash=cash, faces=faces, t_rem=t_rem,
                    yield_curve=yc, spread=spread, need=need,
                    rule="shortest_first",
                )
            df = _df_rem(yc, t_rem, spread)
            mv = faces * df

        cash_hist.append(float(cash))
        face_hist.append(faces.copy())
        mv_hist.append(float(cash + np.sum(mv)))

    return cash_hist, face_hist, mv_hist


# ---------------------------------------------------------------------------
# Unit tests: disinvestment tie-break logic
# ---------------------------------------------------------------------------


@pytest.mark.regression
def test_disinvest_no_double_sell_equal_tenor_buckets():
    """Regression: 2026-03 — double-sell when two bonds had t_rem differing by ~1e-16.

    Reproduces the exact floating-point accumulation condition:
    - Bond 0 (1Y): reset to nominal 1.0 at month 24, decremented 11 more times
    - Bond 1 (3Y): decremented 35 times from 3.0
    Both should have t_rem ≈ 1/12 but bond 1 is ~7.8e-16 SMALLER due to fp accumulation.

    Expected: only bond 0 (lower index) is liquidated; bond 1 face unchanged.
    """
    dt = 1.0 / 12.0

    # Build t_rem with accumulated floating-point error (exactly as in production)
    t_rem_bond0 = 1.0
    for _ in range(11):
        t_rem_bond0 = max(t_rem_bond0 - dt, 0.0)

    t_rem_bond1 = 3.0
    for _ in range(35):
        t_rem_bond1 = max(t_rem_bond1 - dt, 0.0)

    # Confirm the setup: bond1 t_rem < bond0 t_rem by tiny fp amount
    assert t_rem_bond1 < t_rem_bond0, "Setup: bond1 should have smaller t_rem due to accumulation"
    assert abs(t_rem_bond1 - t_rem_bond0) < 1e-14, "Setup: difference must be < 1e-14 (fp noise)"

    t_rem = np.array([t_rem_bond0, t_rem_bond1, 2.0, 7.0, 17.0])
    faces = np.array([267_132.31, 472_616.35, 511_875.80, 646_311.30, 1_149_843.72])
    yc = _flat_yc(0.037)
    df = _df_rem(yc, t_rem)
    need = 7_182.46

    # --- Python _alm_disinvest (with epsilon tie-breaking fix) ---
    cash_result, faces_result = sp._alm_disinvest(
        cash=-need,
        faces=faces.copy(),
        t_rem=t_rem,
        yield_curve=yc,
        spread=0.0,
        need=need,
        rule="shortest_first",
    )

    # Bond 0 must be reduced; bond 1 must be unchanged
    assert faces_result[0] < faces[0], "Bond 0 (lower index) should be liquidated"
    np.testing.assert_allclose(faces_result[1], faces[1], atol=TOL_DOLLAR,
                               err_msg="Bond 1 must NOT be touched (lower t_rem but higher index)")

    # Cash must be restored to >= 0
    assert cash_result >= -TOL_DOLLAR, f"Cash after disinvest should be >= 0, got {cash_result}"

    # Total MV must be preserved (sell at market = cash neutral)
    mv_before = np.sum(faces * df) - need  # net: started with -need cash
    mv_after = cash_result + np.sum(faces_result * _df_rem(yc, t_rem))
    np.testing.assert_allclose(mv_before, mv_after, atol=TOL_DOLLAR,
                               err_msg="Total MV must be conserved through disinvestment")


@pytest.mark.regression
def test_excel_disinvest_no_double_sell_equal_tenor_buckets():
    """Regression: Excel formula sim with 5E-10 threshold must also sell from bond 0 only."""
    dt = 1.0 / 12.0

    t_rem_bond0 = 1.0
    for _ in range(11):
        t_rem_bond0 = max(t_rem_bond0 - dt, 0.0)

    t_rem_bond1 = 3.0
    for _ in range(35):
        t_rem_bond1 = max(t_rem_bond1 - dt, 0.0)

    t_rem = np.array([t_rem_bond0, t_rem_bond1, 2.0, 7.0, 17.0])
    faces = np.array([267_132.31, 472_616.35, 511_875.80, 646_311.30, 1_149_843.72])
    yc = _flat_yc(0.037)
    df = _df_rem(yc, t_rem)
    need = 7_182.46

    cash_result, faces_result = excel_disinvest_shortest_first(-need, faces.copy(), t_rem, df, need)

    assert faces_result[0] < faces[0], "Excel sim: bond 0 should be liquidated"
    np.testing.assert_allclose(faces_result[1], faces[1], atol=TOL_DOLLAR,
                               err_msg="Excel sim: bond 1 must NOT be touched")
    assert cash_result >= -TOL_DOLLAR


def test_disinvest_tie_break_lowest_index_wins():
    """When bonds have exactly equal t_rem (exact float equality), lowest index is sold first."""
    t_rem = np.array([0.25, 0.25, 1.0, 3.0, 8.0])  # bonds 0 and 1 have identical tenor
    faces = np.array([100_000.0, 200_000.0, 300_000.0, 400_000.0, 500_000.0])
    yc = _flat_yc(0.03)
    df = _df_rem(yc, t_rem)
    need = 5_000.0

    cash_py, faces_py = sp._alm_disinvest(
        cash=-need, faces=faces.copy(), t_rem=t_rem,
        yield_curve=yc, spread=0.0, need=need, rule="shortest_first",
    )
    cash_xl, faces_xl = excel_disinvest_shortest_first(-need, faces.copy(), t_rem, df, need)

    # Both engines must sell from bond 0 (lower index), not bond 1
    assert faces_py[0] < faces[0], "Python: bond 0 must be sold first"
    np.testing.assert_allclose(faces_py[1], faces[1], atol=TOL_DOLLAR,
                               err_msg="Python: bond 1 must not be touched")
    assert faces_xl[0] < faces[0], "Excel: bond 0 must be sold first"
    np.testing.assert_allclose(faces_xl[1], faces[1], atol=TOL_DOLLAR,
                               err_msg="Excel: bond 1 must not be touched")

    # Both engines must agree with each other
    np.testing.assert_allclose(faces_py, faces_xl, atol=TOL_DOLLAR,
                               err_msg="Python and Excel must agree on post-disinvest faces")


def test_disinvest_genuinely_different_tenors_sells_shortest():
    """When bond tenors are genuinely different, the shortest is sold first."""
    t_rem = np.array([0.5, 0.1, 2.0, 5.0, 10.0])  # bond 1 is shortest
    faces = np.array([100_000.0, 80_000.0, 300_000.0, 400_000.0, 500_000.0])
    yc = _flat_yc(0.04)
    df = _df_rem(yc, t_rem)
    need = 3_000.0

    _, faces_py = sp._alm_disinvest(
        cash=-need, faces=faces.copy(), t_rem=t_rem,
        yield_curve=yc, spread=0.0, need=need, rule="shortest_first",
    )
    _, faces_xl = excel_disinvest_shortest_first(-need, faces.copy(), t_rem, df, need)

    assert faces_py[1] < faces[1], "Bond 1 (shortest) must be sold first in Python"
    assert faces_xl[1] < faces[1], "Bond 1 (shortest) must be sold first in Excel sim"
    np.testing.assert_allclose(faces_py, faces_xl, atol=TOL_DOLLAR)


def test_excel_disinvest_threshold_is_safely_below_half_epsilon():
    """Guardrail: Excel threshold must not exceed half the epsilon interval.

    If this relationship is broken, adjacent buckets can both trigger when t_rem
    differs only by floating-point noise, recreating the double-sell bug.
    """
    assert EXCEL_DISINVEST_THRESHOLD <= (EXCEL_DISINVEST_EPSILON / 2.0)


@pytest.mark.parametrize("delta", [-4e-10, -1e-10, 0.0, 1e-10, 4e-10])
def test_near_tie_perturbations_still_pick_lowest_index(delta: float):
    """Near-tie fuzz: small perturbations around threshold never violate tie-break.

    For two near-equal buckets, both engines must pick bucket 0 first as long as
    the perturbation stays within the no-double-trigger safety envelope.
    """
    base = 1.0 / 12.0
    t_rem = np.array([base, base + delta, 2.0, 7.0, 17.0])
    faces = np.array([200_000.0, 200_000.0, 300_000.0, 400_000.0, 500_000.0])
    yc = _flat_yc(0.035)
    df = _df_rem(yc, t_rem)
    need = 10_000.0

    _, faces_py = sp._alm_disinvest(
        cash=-need,
        faces=faces.copy(),
        t_rem=t_rem,
        yield_curve=yc,
        spread=0.0,
        need=need,
        rule="shortest_first",
    )
    _, faces_xl = excel_disinvest_shortest_first(-need, faces.copy(), t_rem, df, need)

    assert faces_py[0] < faces[0], "Python should disinvest from lowest-index near-tie bucket"
    np.testing.assert_allclose(
        faces_py[1], faces[1], atol=TOL_DOLLAR,
        err_msg="Python should not touch higher-index near-tie bucket",
    )
    assert faces_xl[0] < faces[0], "Excel sim should disinvest from lowest-index near-tie bucket"
    np.testing.assert_allclose(
        faces_xl[1], faces[1], atol=TOL_DOLLAR,
        err_msg="Excel sim should not touch higher-index near-tie bucket",
    )


# ---------------------------------------------------------------------------
# Full 60-month parity tests
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("flat_rate,aum,annual_benefit", [
    (0.03, 2_000_000.0, 60_000.0),   # no disinvestment needed
    (0.04, 1_800_000.0, 80_000.0),   # light disinvestment
    (0.037, 2_222_430.0, 100_000.0), # tie-break scenario (reproduces 2026-03 bug)
])
def test_alm_60month_parity_python_vs_excel(flat_rate, aum, annual_benefit):
    """Full 60-month step-by-step parity: Python _alm_disinvest vs Excel formula sim.

    Asserts:
    - Cash EOM matches at every month (|diff| <= TOL_DOLLAR)
    - Total asset MV matches at every month (|diff| <= TOL_DOLLAR)
    - Month 60 AUM matches (|diff| <= TOL_DOLLAR)
    """
    yc = _flat_yc(flat_rate)

    # Build synthetic constant CFs (simplified: flat monthly payment)
    monthly_cf = annual_benefit / 12.0
    cfs = np.full(60, monthly_cf)

    py_cash, py_face, py_mv = _run_full_sim(aum, cfs, yc, use_excel_disinvest=False)
    xl_cash, xl_face, xl_mv = _run_full_sim(aum, cfs, yc, use_excel_disinvest=True)

    for m in range(60):
        np.testing.assert_allclose(
            py_cash[m], xl_cash[m], atol=TOL_DOLLAR,
            err_msg=f"Cash mismatch at month {m+1}: Python={py_cash[m]:.6f}, Excel={xl_cash[m]:.6f}",
        )
        np.testing.assert_allclose(
            py_mv[m], xl_mv[m], atol=TOL_DOLLAR,
            err_msg=f"Total MV mismatch at month {m+1}: Python={py_mv[m]:.6f}, Excel={xl_mv[m]:.6f}",
        )
        np.testing.assert_allclose(
            py_face[m], xl_face[m], atol=TOL_DOLLAR,
            err_msg=f"Face array mismatch at month {m+1}",
        )


@pytest.mark.regression
def test_alm_tie_break_scenario_zero_discrepancy():
    """Regression: the exact scenario that produced a 24.00 surplus discrepancy.

    The tie-break at month 35 (1Y and 3Y both nearing maturity simultaneously)
    must yield identical disinvestment in Python and Excel, producing zero
    discrepancy in total AUM at month 60.

    Fixed in 2026-03:
    - alm_excel_ladder.py: < 1E-9 → < 5E-10 threshold
    - spia_projection.py:  added np.arange(n)*1e-9 epsilon to argsort
    """
    flat_rate = 0.037
    aum = 2_222_430.0
    monthly_cf = 100_000.0 / 12.0
    cfs = np.full(60, monthly_cf)
    yc = _flat_yc(flat_rate)

    _, _, py_mv = _run_full_sim(aum, cfs, yc, use_excel_disinvest=False)
    _, _, xl_mv = _run_full_sim(aum, cfs, yc, use_excel_disinvest=True)

    discrepancy = abs(py_mv[59] - xl_mv[59])
    assert discrepancy < TOL_DOLLAR, (
        f"Surplus discrepancy at month 60: {discrepancy:.6f}. "
        f"Python AUM={py_mv[59]:.4f}, Excel AUM={xl_mv[59]:.4f}. "
        "This may indicate the epsilon tie-breaking fix was reverted."
    )
