"""INDEXED_UL product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from product_registry import ProductType, product_label

from products import ProductDefinition, register_product
from iul_projection import (
    IULContract,
    IULProjectionResult,
    liability_path_from_iul_projection,
    price_iul_single_premium,
    price_iul_single_premium_monte_carlo,
)
from build_iul_excel_workbook import IULExcelBuildSpec

from product_excel import _BUILDER_REGISTRY
from products.indexed_ul.ui import INDEXED_UL_ADAPTER, indexed_ul_metric_formatter


DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.INDEXED_UL,
        display_name=product_label(ProductType.INDEXED_UL),
        contract_type=IULContract,
        result_type=IULProjectionResult,
        builder_spec_type=IULExcelBuildSpec,
        adapter=INDEXED_UL_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.INDEXED_UL],
        liability_path_converter=liability_path_from_iul_projection,
        metric_formatter=indexed_ul_metric_formatter,
    )
)


__all__ = [
    "DEFINITION",
    "IULContract",
    "IULExcelBuildSpec",
    "IULProjectionResult",
    "INDEXED_UL_ADAPTER",
    "liability_path_from_iul_projection",
    "price_iul_single_premium",
    "indexed_ul_metric_formatter",
]
