"""WHOLE_LIFE product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from build_wl_excel_workbook import WLExcelBuildSpec
from product_excel import _BUILDER_REGISTRY
from product_registry import ProductType, product_label
from products import ProductDefinition, register_product
from products.whole_life.ui import WHOLE_LIFE_ADAPTER, whole_life_metric_formatter
from wl_projection import (
    WLContract,
    WLProjectionResult,
    liability_path_from_wl_projection,
    price_wl_single_premium,
)

DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.WHOLE_LIFE,
        display_name=product_label(ProductType.WHOLE_LIFE),
        contract_type=WLContract,
        result_type=WLProjectionResult,
        builder_spec_type=WLExcelBuildSpec,
        adapter=WHOLE_LIFE_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.WHOLE_LIFE],
        liability_path_converter=liability_path_from_wl_projection,
        metric_formatter=whole_life_metric_formatter,
    )
)


__all__ = [
    "DEFINITION",
    "WLContract",
    "WLExcelBuildSpec",
    "WLProjectionResult",
    "WHOLE_LIFE_ADAPTER",
    "liability_path_from_wl_projection",
    "price_wl_single_premium",
    "whole_life_metric_formatter",
]
