"""VARIABLE_ANNUITY product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from product_registry import ProductType, product_label

from products import ProductDefinition, register_product
from va_projection import (
    VAContract,
    VAProjectionResult,
    liability_path_from_va_projection,
    price_va_single_premium,
    price_va_single_premium_monte_carlo,
)
from build_va_excel_workbook import VAExcelBuildSpec

from product_excel import _BUILDER_REGISTRY
from products.variable_annuity.ui import VARIABLE_ANNUITY_ADAPTER, variable_annuity_metric_formatter


DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.VARIABLE_ANNUITY,
        display_name=product_label(ProductType.VARIABLE_ANNUITY),
        contract_type=VAContract,
        result_type=VAProjectionResult,
        builder_spec_type=VAExcelBuildSpec,
        adapter=VARIABLE_ANNUITY_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.VARIABLE_ANNUITY],
        liability_path_converter=liability_path_from_va_projection,
        metric_formatter=variable_annuity_metric_formatter,
    )
)


__all__ = [
    "DEFINITION",
    "VAContract",
    "VAExcelBuildSpec",
    "VAProjectionResult",
    "VARIABLE_ANNUITY_ADAPTER",
    "liability_path_from_va_projection",
    "price_va_single_premium",
    "variable_annuity_metric_formatter",
]
