"""FIA product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from annuity_model.build_fia_excel_workbook import FIAExcelBuildSpec
from annuity_model.fia_projection import (
    FIAContract,
    FIAProjectionResult,
    liability_path_from_fia_projection,
    price_fia_single_premium,
    price_fia_single_premium_monte_carlo,
)
from annuity_model.product_excel import _BUILDER_REGISTRY
from annuity_model.product_registry import ProductCapabilities, ProductType, _validate_fia
from annuity_model.products import ProductDefinition, register_product
from annuity_model.products.fia.ui import FIA_ADAPTER, fia_metric_formatter, fia_ui_config

DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.FIA,
        display_name="FIA (fixed indexed annuity)",
        contract_type=FIAContract,
        result_type=FIAProjectionResult,
        builder_spec_type=FIAExcelBuildSpec,
        adapter=FIA_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.FIA],
        liability_path_converter=liability_path_from_fia_projection,
        metric_formatter=fia_metric_formatter,
        capabilities=ProductCapabilities(
            supports_economic_scenario=True, supports_monte_carlo=True
        ),
        ui_config=fia_ui_config,
        mortality_mode_options=("synthetic", "qx_csv", "rp2014_mp2016"),
        default_mortality_mode="rp2014_mp2016",
        validator=_validate_fia,
        order=4,
    )
)


__all__ = [
    "DEFINITION",
    "FIAContract",
    "FIAExcelBuildSpec",
    "FIAProjectionResult",
    "FIA_ADAPTER",
    "liability_path_from_fia_projection",
    "price_fia_single_premium",
    "price_fia_single_premium_monte_carlo",
    "fia_metric_formatter",
    "fia_ui_config",
]
