"""MYGA product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from product_registry import ProductType, product_label

from products import ProductDefinition, register_product
from myga_projection import (
    MYGAContract,
    MYGAProjectionResult,
    liability_path_from_myga_projection,
    price_myga_single_premium,
)
from build_myga_excel_workbook import MYGAExcelBuildSpec

from product_excel import _BUILDER_REGISTRY
from products.myga.ui import MYGA_ADAPTER, myga_metric_formatter


DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.MYGA,
        display_name=product_label(ProductType.MYGA),
        contract_type=MYGAContract,
        result_type=MYGAProjectionResult,
        builder_spec_type=MYGAExcelBuildSpec,
        adapter=MYGA_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.MYGA],
        liability_path_converter=liability_path_from_myga_projection,
        metric_formatter=myga_metric_formatter,
    )
)


__all__ = [
    "DEFINITION",
    "MYGAContract",
    "MYGAExcelBuildSpec",
    "MYGAProjectionResult",
    "MYGA_ADAPTER",
    "liability_path_from_myga_projection",
    "price_myga_single_premium",
    "myga_metric_formatter",
]
