"""FIA product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from build_fia_excel_workbook import FIAExcelBuildSpec
from fia_projection import (
    FIAContract,
    FIAProjectionResult,
    liability_path_from_fia_projection,
    price_fia_single_premium,
    price_fia_single_premium_monte_carlo,
)
from product_excel import _BUILDER_REGISTRY
from product_registry import ProductType, product_label
from products import ProductDefinition, register_product
from products.fia.ui import FIA_ADAPTER, fia_metric_formatter

DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.FIA,
        display_name=product_label(ProductType.FIA),
        contract_type=FIAContract,
        result_type=FIAProjectionResult,
        builder_spec_type=FIAExcelBuildSpec,
        adapter=FIA_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.FIA],
        liability_path_converter=liability_path_from_fia_projection,
        metric_formatter=fia_metric_formatter,
    )
)


__all__ = [
    "DEFINITION",
    "FIAContract",
    "FIAExcelBuildSpec",
    "FIAProjectionResult",
    "FIA_ADAPTER",
    "liability_path_from_fia_projection",
    "price_fia_single_premium",
    "price_fia_single_premium_monte_carlo",
    "fia_metric_formatter",
]
