"""UNIVERSAL_LIFE product subpackage.

See ``products.spia`` for the pattern; this module is generated by
Phase 0/1/.../7 of ``docs/seven_product_rollout_plan.md``.
"""

from __future__ import annotations

from build_ul_excel_workbook import ULExcelBuildSpec
from product_excel import _BUILDER_REGISTRY
from product_registry import ProductType, product_label
from products import ProductDefinition, register_product
from products.universal_life.ui import UNIVERSAL_LIFE_ADAPTER, universal_life_metric_formatter
from ul_projection import (
    ULContract,
    ULProjectionResult,
    liability_path_from_ul_projection,
    price_ul_single_premium,
)

DEFINITION = register_product(
    ProductDefinition(
        product_type=ProductType.UNIVERSAL_LIFE,
        display_name=product_label(ProductType.UNIVERSAL_LIFE),
        contract_type=ULContract,
        result_type=ULProjectionResult,
        builder_spec_type=ULExcelBuildSpec,
        adapter=UNIVERSAL_LIFE_ADAPTER,
        builder=_BUILDER_REGISTRY[ProductType.UNIVERSAL_LIFE],
        liability_path_converter=liability_path_from_ul_projection,
        metric_formatter=universal_life_metric_formatter,
    )
)


__all__ = [
    "DEFINITION",
    "ULContract",
    "ULExcelBuildSpec",
    "ULProjectionResult",
    "UNIVERSAL_LIFE_ADAPTER",
    "liability_path_from_ul_projection",
    "price_ul_single_premium",
    "universal_life_metric_formatter",
]
